subscribed_topic_names:
  map2d: /slam/map
  map3d: /octomap_full
occupied_cell_thres: 0.5
#kinect_frame
frames_to_track: [kinect_link]
published_topic_names:
  space_kinect_link: space_kinect
  surface_kinect_link: surface_kinect
sensor_range:
  kinect_link: 2.2
sensor_hfov:
  kinect_link: 58
sensor_vfov:
  kinect_link: 45
max_height:
  kinect_link: 1.20
exploration_state:
  kinect_link: true
identification_state:
  kinect_link: true
hold_state:
  kinect_link: true
