footprint:
  width: 0.58
  height: 0.42

map_origin: SLAM
occupied_cell_thres: 0.5
global_frame: /map
robot_base_frame: /base_footprint
max_height: 1.00

subscribed_topic_names:
  map2d: /slam/map
  map3d: /octomap_full

frames_to_track: [kinect_rgb_frame]

# kinect_rgb_frame
kinect_rgb_frame:
  published_topic_names:
    space: kinect_space
    surface: kinect_surface
  sensor_range: 2.2
  sensor_hfov: 58
  sensor_vfov: 45
  exploration_state: true
  identification_state: true
  hold_state: true
