subscribed_topic_names:
  map: /map
frames_to_track: [kinect]
published_topic_names:
  space_kinect: space_kinect
  surface_kinect: surface_kinect
sensor_range:
  kinect: 10
sensor_hfov:
  kinect: 60
sensor_vfov:
  kinect: 40
max_height:
  kinect: 1.20
exploration_state:
  kinect: true
identification_state:
  kinect: true
hold_state:
  kinect: true
