subscribed_topic_names:
  map2d: /slam/map
  map3d: /octomap_full
occupied_cell_thres: 0.5
#kinect_frame
frames_to_track: [kinect_rgb_frame]
published_topic_names:
  space_kinect_rgb_frame: space_kinect
  surface_kinect_rgb_frame: surface_kinect
sensor_range:
  kinect_rgb_frame: 2.2
sensor_hfov:
  kinect_rgb_frame: 58
sensor_vfov:
  kinect_rgb_frame: 45
max_height:
  kinect_rgb_frame: 1.20
exploration_state:
  kinect_rgb_frame: true
identification_state:
  kinect_rgb_frame: true
hold_state:
  kinect_rgb_frame: true
