map_type: SLAM
global_frame: /map
object_names:
  hole: hole
  obstacle: obstacle
  hazmat: hazmat
  qr: qr
  thermal: thermal
  victim_image: victim_image
  motion: motion
  sound: sound
  co2: co2
  landoltc: landoltc
  datamatrix: datamatrix
  victim: victim

subscribed_topic_names:
  hole: /vision/holes_direction_alert
  obstacle: /vision/obstacle_alert
  thermal: /vision/thermal_direction_alert
  qr: /vision/qr_alert
  hazmat: /vision/hazmat_alert
  landoltc: /vision/landoltc_alert
  data_matrix: /vision/dataMatrix_alert
  victim_image: /vision/victim_direction_alert
  co2: /sensor_processing/co2_alert
  motion: /vision/motion_alert
  sound: /sensor_processing/sound_direction_alert
  map: /slam/map
published_topic_names:
  world_model: /data_fusion/world_model
  qr_notification: /data_fusion/qr_notification
  obstacle_info: /data_fusion/obstacle_info
  robocup_score: /data_fusion/robocup_score
  global_probabilities: /data_fusion/signs_of_life
action_server_names:
  delete_victim: /data_fusion/delete_victim
  validate_victim: /data_fusion/validate_victim
service_server_names:
  get_objects: /data_fusion/get_objects
  get_markers: /data_fusion/get_markers
  geotiff: /data_fusion/geotiffSrv
  flush_queues: /data_fusion/flush_queues

