map_type: SLAM
global_frame: /map
object_names:
  hole: hole
  obstacle: obstacle
  hazmat: hazmat
  qr: qr
  thermal: thermal
  visual_victim: visual_victim
  motion: motion
  sound: sound
  co2: co2
  landoltc: landoltc
  datamatrix: datamatrix
  victim: victim

subscribed_topic_names:
  hole: /vision/holes_direction_alert
  obstacle: /vision/obstacle_alert
  thermal: /vision/thermal_direction_alert
  qr: /vision/qr_alert
  hazmat: /vision/hazmat_alert
  landoltc: /vision/landoltc_alert
  data_matrix: /vision/data_matrix_alert
  visual_victim: /vision/victim_direction_alert
  co2: /sensor_processing/co2_alert
  motion: /vision/motion_alert
  sound: /sound/complete_alert/poi
  map: /slam/map
published_topic_names:
  world_model: /data_fusion/world_model
  qr_info: /data_fusion/qr_info
  obstacle_info: /data_fusion/obstacle_info
  robocup_score: /data_fusion/robocup_score
  victim_probabilities: /data_fusion/signs_of_life
action_server_names:
  target_victim: /data_fusion/target_victim
  delete_victim: /data_fusion/delete_victim
  validate_victim: /data_fusion/validate_victim
service_server_names:
  get_objects: /data_fusion/get_objects
  get_markers: /data_fusion/get_markers
  get_geotiff: /data_fusion/get_geotiff
  get_victim_probabilities: /data_fusion/get_probabilities
  flush_queues: /data_fusion/flush_queues
