map_type: SLAM
global_frame: /map
object_names:
  hole: HOLE
  hazmat: HAZMAT
  qr: QR
  thermal: THERMAL
  face: FACE
  motion: MOTION
  sound: SOUND
  co2: CO2
  landoltc: LANDOLTC
  datamatrix: DATAMATRIX
  victim: VICTIM

subscribed_topic_names:
  holeDirection: /vision/holes_direction_alert
  thermalDirection: /sensor_processing/thermal_direction_alert
  qr: /vision/qr_alert
  hazmat: /vision/hazmat_alert
  landoltc: /vision/landoltc_alert
  dataMatrix: /vision/dataMatrix_alert
  faceDirection: /vision/victim_direction_alert
  co2Direction: /sensor_processing/co2_alert
  motionDirection: /vision/motion_alert
  soundDirection: /sensor_processing/sound_direction_alert
  map: /slam/map
published_topic_names:  
  world_model: /data_fusion/world_model
  qr_notification: /data_fusion/qr_notification
  robocup_score: /data_fusion/robocup_score
  global_probabilities: /data_fusion/signs_of_life
action_server_names:
  delete_victim: /data_fusion/delete_victim
  validate_victim: /data_fusion/validate_victim
service_server_names:
  get_objects: /data_fusion/get_objects
  get_markers: /data_fusion/get_markers
  geotiff: /data_fusion/geotiffSrv
  flush_queues: /data_fusion/flush_queues
  
