subscribed_topic_names:
  holeDirection: /vision/hole_direction_alert
  thermalDirection: /sensor_processing/thermal_direction_alert
  qr: /vision/qr_alert
  hazmat: /vision/hazmat_alert
  landoltc: /vision/landoltc_alert
  dataMatrix: /vision/dataMatrix_alert
  faceDirection: /vision/face_direction_alert
  co2Direction: /sensor_processing/co2_alert
  motionDirection: /vision/motion_alert
  soundDirection: /sensor_processing/sound_direction_alert
  map: /slam/map
published_topic_names:  
  world_model : /data_fusion/world_model
  qr_notification : qr_notification
  robocup_score : robocup_score
action_server_names:
  delete_victim: delete_victim
  validate_victim: validate_victim
service_server_names:
  get_objects: /data_fusion/get_objects
  get_markers: /data_fusion/get_markers
  geotiff: /data_fusion/geotiffSrv
  flush_queues: /data_fusion/flush_queues
      
