subscribed_topic_names:
  holeDirection: /data_fusion/victim_fusion/hole_direction_alert
  thermalDirection: /sensor_processors/thermal_direction_alert
  qr: /vision/qr_alert
  hazmat: /vision/hazmat_alert
  faceDirection: /vision/face_direction_alert
  co2Direction: /sensor_processors/co2_direction_alert
  motionDirection: /vision/motion_alert
  soundDirection: /sensor_processors/sound_direction_alert
  currentVictim: /data_fusion/victim_fusion/selected_victim
  map: /slam/map
published_topic_names:  
  victims : victims
  victim_found : victim_found
  victim_update : victim_update
  victim_verified : victim_verified
  valid_victims_counter : valid_victims_counter
  qr_notification : qr_notification
  robocup_score : robocup_score
action_server_names:
  get_victims: get_victims
  delete_current_victim: delete_current_victim
  validate_victim: validate_victim
service_server_names:
  get_objects: /data_fusion/get_objects
  get_markers: /data_fusion/get_markers
  geotiff: /data_fusion/geotiffSrv
  flush_queues: /data_fusion/flush_queues
      
